package com.zdonnell.androideveapi.shared.contract;

public enum ContractStatus {
	OUTSTANDING, DELETED, COMPLETED, FAILED, COMPLETEDBYISSUER, COMPLETEDBYCONTRACTOR, CANCELLED, REJECTED, REVERSED, INPROGRESS
}